object Versions {
    const val androidApplication = "8.1.0"
    const val androidLibrary = "8.1.0"
    const val gradlePlugin = "8.1.0"
    const val kotlin = "1.9.0"
    const val kspVersion = "1.0.13"
    const val coreKtx = "1.10.1"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val material3 = "1.1.1"
    const val constraintLayout = "2.1.4"
    const val lifecycle = "2.6.1"
    const val kotlinCoroutine = "1.6.4"
    const val fragment = "1.6.1"
    const val navigation = "2.7.0"
    const val daggerHilt = "2.46.1"
    const val retrofit = "2.9.0"
    const val room = "2.5.0"
    const val glide = "4.16.0"
    const val jUnit = "4.13.2"
    const val jUnitExt = "1.1.5"
    const val espresso = "3.5.1"
}